# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba75eb91d371c93f026069b31232ce2569084b4ede09a270c1af8c8537428695fe542145138422cc864480ea3d6db1ae353045000aae97822b39550ad66572fb

test:
  secret_key_base: 5f1d7ffc8409008b4a04868863593cdba783f330e711edddfb83ac95fbe3ed0160f59398863f78fe1cef70bcbbcbe280b9066623bd998dcc245e3a36cd6b4953

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
